
#version: "3"
#services:
#  mysqldb:
#    container_name: mysqldb
#    image: mysql:8
#    networks:
#      - spring-mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=project
#    restart: unless-stopped
#  # APP*****************************************
#  springbootapp:
#    image: springbootapp:latest
#
#    container_name: springbootapp
#    ports:
#      - "8080:8080"
#    networks:
#      - spring-mysql
#    depends_on:
#      - mysqldb
#    links:
#      - mysqldb
#
#networks:
#  spring-mysql:
version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=project
      - MYSQL_USER=testuser
    restart: unless-stopped
    ports:
      - "3307:3306"
  springboot-docker:
    image: springboot-docker
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/project?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"

    depends_on:
      - mysql-standalone


