
version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    networks:
      - spring-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project
    restart: unless-stopped
  # APP*****************************************
  springbootapp:
    image: springbootapp:latest

    container_name: springbootapp
    ports:
      - "8080:8080"
    networks:
      - spring-mysql
    depends_on:
      - mysqldb
    links:
      - mysqldb

networks:
  spring-mysql: